// Regenerates src/icon.ts from assets/catcard-icon.svg.
import { readFileSync, writeFileSync } from 'node:fs';

const svg = readFileSync(new URL('../assets/catcard-icon.svg', import.meta.url), 'utf8')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/>\s+</g, '><')
  .replace(/\s+/g, ' ')
  .trim();

writeFileSync(
  new URL('../src/icon.ts', import.meta.url),
  `// Generated by scripts/build-icon.mjs from assets/catcard-icon.svg. Do not edit.

/** CatCard icon as a base64 SVG data URI (the form Wallet Standard requires; also used for EIP-6963). */
export const CATCARD_ICON: \`data:image/svg+xml;base64,\${string}\` =
  'data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}';
`,
);
